# Data Profiling

## Objective

The objective of this notebook is to perform an initial assessment of the Olist dataset, understand its relational structure, evaluate data quality, and identify potential issues before business analysis.

---

**Author:** Zhuyi (Chelsea) Huang

**Project:** Business Analytics AI Platform

**Dataset:** Olist Brazilian E-Commerce Public Dataset

In [1]:
import os
import pandas as pd

pd.set_option("display.max_columns", None)

In [2]:
data_path = "../data"

csv_files = sorted([f for f in os.listdir(data_path) if f.endswith(".csv")])

csv_files

['olist_customers_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_orders_dataset.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'product_category_name_translation.csv']

In [3]:
datasets = {}

for file in csv_files:
    datasets[file] = pd.read_csv(os.path.join(data_path, file))

print(f"{len(datasets)} tables loaded.")

9 tables loaded.

In [4]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.shape)

============================================================
olist_customers_dataset.csv
(99441, 5)
============================================================
olist_geolocation_dataset.csv
(1000163, 5)
============================================================
olist_order_items_dataset.csv
(112650, 7)
============================================================
olist_order_payments_dataset.csv
(103886, 5)
============================================================
olist_order_reviews_dataset.csv
(99224, 7)
============================================================
olist_orders_dataset.csv
(99441, 8)
============================================================
olist_products_dataset.csv
(32951, 9)
============================================================
olist_sellers_dataset.csv
(3095, 4)
============================================================
product_category_name_translation.csv
(71, 2)

In [5]:
summary = []

for name, df in datasets.items():
    summary.append({
        "Table": name.replace("_dataset.csv", ""),
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

summary = pd.DataFrame(summary)

summary

,Table,Rows,Columns,Missing Values,Duplicate Rows
0,olist_customers,99441,5,0,0
1,olist_geolocation,1000163,5,0,261831
2,olist_order_items,112650,7,0,0
3,olist_order_payments,103886,5,0,0
4,olist_order_reviews,99224,7,145903,0
5,olist_orders,99441,8,4908,0
6,olist_products,32951,9,2448,0
7,olist_sellers,3095,4,0,0
8,product_category_name_translation.csv,71,2,0,0

In [6]:
datasets["olist_orders_dataset.csv"].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
datasets["olist_customers_dataset.csv"].head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [8]:
datasets["olist_order_items_dataset.csv"].head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
datasets["olist_products_dataset.csv"].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [10]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print(df.dtypes)

============================================================
olist_customers_dataset.csv
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
============================================================
olist_geolocation_dataset.csv
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object
============================================================
olist_order_items_dataset.csv
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object
============================================================
olist_order_payments_dataset.csv
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object
============================================================
olist_order_reviews_dataset.csv
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object
============================================================
olist_orders_dataset.csv
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object
============================================================
olist_products_dataset.csv
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
============================================================
olist_sellers_dataset.csv
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object
============================================================
product_category_name_translation.csv
product_category_name            object
product_category_name_english    object
dtype: object

In [11]:
for name, df in datasets.items():
    missing = df.isnull().sum()

    missing = missing[missing > 0]

    if len(missing) > 0:
        print("=" * 60)
        print(name)
        print(missing)

============================================================
olist_order_reviews_dataset.csv
review_comment_title      87656
review_comment_message    58247
dtype: int64
============================================================
olist_orders_dataset.csv
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64
============================================================
olist_products_dataset.csv
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64